name: flutter_storage_info_example
description: "Demonstrates how to use the flutter_storage_info plugin."


environment:
  sdk: '>=3.3.0 <4.0.0'


dependencies:
  flutter:
    sdk: flutter

  flutter_storage_info:
    path: ../

  cupertino_icons: ^1.0.6
# flutter_storage_info: ^0.0.1

dev_dependencies:
  integration_test:
    sdk: flutter
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true