name: flutter_storage_info
description: "A Flutter plugin providing methods to retrieve information about device storage, including internal and external storage space. Useful for apps needing to monitor storage usage or manage file storage efficiently."
version: 0.1.0
homepage: https://github.com/JaberQayad/flutter_storage_info.git

environment:
  sdk: '>=3.3.0 <4.0.0'
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.example.flutter_storage_info
        pluginClass: FlutterStorageInfoPlugin
