name: flutter_storage_info
description: "Flutter plugin to get storage info of the device."
<<<<<<< HEAD
version: 0.0.3
=======
version: 0.0.1
>>>>>>> 535a1c58b1c7dc832e79f98f9e0017a5b60bb06c
homepage: https://github.com/JaberQayad/flutter_storage_info.git

environment:
  sdk: '>=3.3.0 <4.0.0'
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.example.flutter_storage_info
        pluginClass: FlutterStorageInfoPlugin
