name: flutter_storage_info
description: Flutter plugin for retrieving storage information. Easily get details on device storage usage. Reliable and efficient.
version: 0.0.5
homepage: https://github.com/JaberQayad/flutter_storage_info.git

repository: https://github.com/JaberQayad/flutter_storage_info.git


environment:
  sdk: '>=3.3.0 <4.0.0'
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.example.flutter_storage_info
        pluginClass: FlutterStorageInfoPlugin
